# Generated by Django 3.2 on 2021-10-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Payment_Mpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveSmallIntegerField(default=500)),
                ('account_duration_period', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Years', 'Years')], default='Days', max_length=6)),
                ('user_account_duration', models.PositiveIntegerField(default='1')),
                ('user_account_plan', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Advanced', 'Advanced')], default=' ', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Payment Plans',
            },
        ),
    ]
