# Generated by Django 3.2 on 2021-10-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_payment_mpesa',
            old_name='account_duration_period',
            new_name='account_valid_days',
        ),
        migrations.RemoveField(
            model_name='account_payment_mpesa',
            name='user_account_plan',
        ),
    ]
