# Generated by Django 3.2 on 2021-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0002_auto_20211014_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_payment_mpesa',
            name='account_valid_days',
            field=models.CharField(choices=[('365', '365'), ('730', '730'), ('1095', '1095')], default='Days', max_length=4),
        ),
    ]
