# Generated by Django 3.2 on 2021-10-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0003_alter_account_payment_mpesa_account_valid_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_payment_mpesa',
            name='account_phone_number',
            field=models.SmallIntegerField(default='2547'),
        ),
    ]
