# Generated by Django 3.2 on 2021-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0006_alter_account_payment_mpesa_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_payment_mpesa',
            name='account_phone_number',
            field=models.PositiveSmallIntegerField(default='2547xxxxxx05', max_length=12),
        ),
    ]
