# Generated by Django 3.2 on 2021-10-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0009_alter_account_payment_mpesa_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_payment_mpesa',
            name='amount_paid',
            field=models.PositiveSmallIntegerField(choices=[('250', '250'), ('500', '500'), ('1000', '1000')], default=500),
        ),
    ]
