# Generated by Django 3.2 on 2021-10-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0010_alter_account_payment_mpesa_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_payment_mpesa',
            name='amount_paid',
            field=models.CharField(choices=[('250', '250'), ('500', '500'), ('1000', '1000')], default=500, max_length=4),
        ),
    ]
