# Generated by Django 3.2 on 2021-10-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BizDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bussiness_Type', models.CharField(default=' ', max_length=100)),
                ('bussiness_Logo', models.CharField(default='any word', max_length=13)),
                ('bussiness_Name', models.CharField(default=' ', max_length=100, unique=True)),
                ('bussiness_Info', models.CharField(default=' ', max_length=100, unique=True)),
                ('bussiness_Description', models.TextField(default='')),
                ('about_Services_Offered', models.TextField(default=' ')),
                ('bussiness_Goals', models.TextField(default=' ')),
                ('week_day', models.CharField(choices=[('Days', (('Monday - Wednessday ', 'Monday - Wednessday'), ('Monday - Thursday ', 'Monday - Thursday'), ('Monday - Friday', 'Monday - Friday'), ('Monday - Saturday', 'Monday - Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')))], default='Monday - Friday', max_length=25)),
                ('time', models.CharField(choices=[('Time', (('Open', 'Open'), ('Closed', 'Closed'), ('8.00 AM - 3.00 PM', '8.00 AM - 3.00 PM'), ('8.00 AM - 4.00 PM', '8.00 AM - 4.00 PM'), ('8.00 AM - 5.00 PM', '8.00 AM - 5.00 PM'), ('9.00 AM - 3.00 PM', '9.00 AM - 3.00 PM'), ('9.00 AM - 4.00 PM', '9.00 AM - 4.00 PM'), ('9.00 AM - 5.00 PM', '9.00 AM - 5.00 PM'), ('9.00 AM - 1.00 PM', '9.00 AM - 1.00 PM'), ('9.00 AM - 2.00 PM', '9.00 AM - 2.00 PM'), ('9.00 AM - 3.00 PM', '10.00 AM - 3.00 PM'), ('10.00 AM - 3.00 PM', '10.00 AM - 3.00 PM'), ('10.00 AM - 4.00 PM', '10.00 AM - 4.00 PM'), ('10.00 AM - 5.00 PM', '10.00 AM - 5.00 PM'), ('10.00 AM - 1.00 PM', '10.00 AM - 1.00 PM'), ('10.00 AM - 2.00 PM', '10.00 AM - 2.00 PM'), ('11.00 AM - 1.00 PM', '11.00 AM - 1.00 PM'), ('11.00 AM - 2.00 PM', '11.00 AM - 2.00 PM'), ('11.00 AM - 3.00 PM', '11.00 AM - 3.00 PM')))], default='9.00 AM - 5.00 PM', max_length=18)),
                ('weekend', models.CharField(choices=[('Days', (('Monday - Wednessday ', 'Monday - Wednessday'), ('Monday - Thursday ', 'Monday - Thursday'), ('Monday - Friday', 'Monday - Friday'), ('Monday - Saturday', 'Monday - Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')))], default='Saturday', max_length=25)),
                ('weekend_opens', models.CharField(choices=[('Time', (('Open', 'Open'), ('Closed', 'Closed'), ('8.00 AM - 3.00 PM', '8.00 AM - 3.00 PM'), ('8.00 AM - 4.00 PM', '8.00 AM - 4.00 PM'), ('8.00 AM - 5.00 PM', '8.00 AM - 5.00 PM'), ('9.00 AM - 3.00 PM', '9.00 AM - 3.00 PM'), ('9.00 AM - 4.00 PM', '9.00 AM - 4.00 PM'), ('9.00 AM - 5.00 PM', '9.00 AM - 5.00 PM'), ('9.00 AM - 1.00 PM', '9.00 AM - 1.00 PM'), ('9.00 AM - 2.00 PM', '9.00 AM - 2.00 PM'), ('9.00 AM - 3.00 PM', '10.00 AM - 3.00 PM'), ('10.00 AM - 3.00 PM', '10.00 AM - 3.00 PM'), ('10.00 AM - 4.00 PM', '10.00 AM - 4.00 PM'), ('10.00 AM - 5.00 PM', '10.00 AM - 5.00 PM'), ('10.00 AM - 1.00 PM', '10.00 AM - 1.00 PM'), ('10.00 AM - 2.00 PM', '10.00 AM - 2.00 PM'), ('11.00 AM - 1.00 PM', '11.00 AM - 1.00 PM'), ('11.00 AM - 2.00 PM', '11.00 AM - 2.00 PM'), ('11.00 AM - 3.00 PM', '11.00 AM - 3.00 PM')))], default='10.00 AM - 2.00 PM', max_length=18)),
                ('bussiness_Facebook', models.CharField(default=' ', max_length=100)),
                ('bussiness_Instagram', models.CharField(default=' ', max_length=100)),
                ('bussiness_Whatsapp', models.CharField(default='+2547 ', max_length=12)),
                ('bussiness_Linkedin', models.CharField(default=' ', max_length=100)),
                ('bussiness_Email', models.EmailField(default=' ', max_length=254)),
                ('bussiness_Address', models.CharField(default=' ', max_length=50)),
                ('bussiness_Location', models.CharField(default='Nairobi,Kenya ', max_length=50)),
                ('bussiness_Background_Image', models.ImageField(default='homepage/bs4.jpg', upload_to='homepage/')),
                ('image_of_bussiness', models.ImageField(default='bussiness/default.jpg', upload_to='bussiness/')),
                ('image_of_manager', models.ImageField(default='manager/default.jpg', upload_to='manager/')),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Created', 'Created'), ('Active', 'Active'), ('Deactive', 'Deactive')], default='active', max_length=10)),
                ('bussiness_Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bussiness Information',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='BussinessProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(default=' ', max_length=50)),
                ('productDescription', models.CharField(default=' ', max_length=300)),
                ('productImage', models.ImageField(upload_to='')),
                ('bussinessOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBizDetails.bizdetails')),
            ],
            options={
                'verbose_name_plural': 'Bussiness Products',
            },
        ),
        migrations.CreateModel(
            name='BusinessTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullNameOfMember', models.CharField(default=' ', max_length=50)),
                ('roleOfMember', models.CharField(default=' ', max_length=50)),
                ('photoOfMember', models.ImageField(upload_to='')),
                ('bussinessOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBizDetails.bizdetails')),
            ],
            options={
                'verbose_name_plural': 'Bussiness Team Members',
            },
        ),
        migrations.CreateModel(
            name='BizServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default=' ', max_length=200)),
                ('service_photo', models.ImageField(upload_to='')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
