# Generated by Django 3.2 on 2021-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBizDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizdetails',
            name='bussiness_Facebook',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bizdetails',
            name='bussiness_Instagram',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bizdetails',
            name='bussiness_Linkedin',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
