# Generated by Django 3.2 on 2021-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBizDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizservices',
            name='service_photo',
            field=models.ImageField(upload_to='services'),
        ),
    ]
