# Generated by Django 3.2 on 2021-10-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBizDetails', '0002_auto_20211019_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizdetails',
            old_name='bussiness_Home',
            new_name='bussiness_Background_Image',
        ),
    ]
