# Generated by Django 3.2 on 2021-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBizDetails', '0002_alter_bizservices_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizservices',
            name='service_title',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
