# Generated by Django 3.2 on 2021-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBizDetails', '0003_rename_bussiness_home_bizdetails_bussiness_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizdetails',
            name='bussiness_Address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='bizdetails',
            name='bussiness_Location',
            field=models.CharField(default='Nairobi,Kenya ', max_length=50),
        ),
    ]
